
//ADD TODO
export const ADD_TODO_REQUEST = "GET_TODO_REQUEST";
//UPDATE TODO
export const UPDATE_TODO_REQUEST="UPDATE_TODO_REQUEST";
//DELETE TODO
export const DELETE_TODO_REQUEST="DELETE_TODO_REQUEST";

